name: Terraform setup remote state backend

on: workflow_dispatch
    branches:
      - main
    paths:
    - build_remote_backend/**

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5" 

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform format
       id: fmt
       run: terraform fmt #-check
    
      - name: Terraform validate
       id: validate
       run: terraform validate

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

      