name: Terraform setup remote state backend

on: 
  workflow_dispatch:
    branches:
      - main
    paths:
      - build_remote_backend/**

env:
 # verbosity setting for Terraform logs
 # TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: zsh
        # We keep Terraform files in the terraform directory.
        working-directory: ./build_remote_backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5" 

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform format
        id: fmt
        run: terraform fmt
    
      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

      