name: Terraform With Remote Backend

on: 
  workflow_dispatch:
    branches:
      - main
    paths:
      - terraform/**

permissions:
  contents: read
  id-token: write
#   pull-requests: write
#   issues: write

env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_DEFAULT_REGION: us-west-2

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::226109441954:role/Github_OIDC_Test
          aws-region: us-west-2
          role-session-name: Github-OIDC-TERRAFORM

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5" 

      - name: Configure remote backend
        run: |
          terraform init -backend-config="bucket=github-actions-test-s3-bucket" \
                         -backend-config="key=terraform.tfstate" \
                         -backend-config="region=us-west-2"

      - name: Terraform format
        id: fmt
        run: terraform fmt
    
      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
