name: Terraform With Remote Backend

on: 
  workflow_dispatch:
    branches:
      - main
    paths:
      - terraform/**

env:
 # verbosity setting for Terraform logs
 # TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5" 

      - name: Configure remote backend
        run: |
          terraform init -backend-config="bucket=github-actions-test-s3-bucket" \
                         -backend-config="key=terraform.tfstate" \
                         -backend-config="region=us-west-2"

      - name: Terraform format
        id: fmt
        run: terraform fmt
    
      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
