name: arn terraform test

on: 
  workflow_dispatch:
    branches:
      - main
    paths:
      - terraform/**

env:
 # verbosity setting for Terraform logs
    TF_DIR: ./terraform
#  # Credentials for deployment to AWS
#  AWS_DEFAULT_REGION: us-west-2

jobs:
  terraform:
    permissions:
        contents: read
        id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform d irectory.
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::226109441954:role/github_oidc_admin_test
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5" 

      - name: Configure remote backend
        run: |
          terraform init -backend-config="bucket=github-actions-test-s3-bucket" \
                         -backend-config="key=terraform.tfstate" \
                         -backend-config="region=us-west-2"

      - name: Terraform format
        id: fmt
        run: terraform fmt
    
      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
